sudo: required
language: go

env:
  global:
    - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./test-reporter
  - chmod +x ./test-reporter
  - ./test-reporter before-build

script:
  - make test
  - go test -coverprofile c.out .
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - ./test-reporter format-coverage -t gocov --prefix phonedata
  - ./test-reporter upload-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - 614422099@qq.com
    on_success: always
    on_failure: always
