sudo: required
language: go

env:
  - GO111MODULE=true

go:
  - 1.11.x
  - 1.12.x

script:
  - make test

notifications:
  email:
    recipients:
      - 614422099@qq.com
    on_success: always
    on_failure: always