version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\$username\$project

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.12.7

init:
  - git config --global core.autocrlf input

stack: go 1.14.2
build: false
deploy: false

test_script:
  - go test -v -bench=".*" -benchmem

notifications:
  - provider: Email
    to:
      - 614422099@qq.com
    subject: '[phonedata] win build'
    message: 新的编译信息
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
