version: "{build}"

# Source Config
clone_folder: C:\projects\phonedata

# Build host

environment:
  GOPATH: c:\gopath

stack: go 1.14

build: false
deploy: false

before_test:
  - go vet ./...

test_script:
  - go version
  - go env
  - go test -v -bench=".*" -benchmem

notifications:
  - provider: Email
    to:
      - 614422099@qq.com
    subject: '[phonedata] win build'
    message: 新的编译信息
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
