version: 1.0.{build}
build:
  verbosity: minimal
test_script:
- sh: go env
- sh: go test -v -bench=".*" -benchmem
notifications:
- provider: Email
  to:
  - 614422099@qq.com
  subject: '[phonedata] win build'
  message: 新的编译信息
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
